spring:
  profiles:
    include: route
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.11.128:8848
        username: nacos
        password: nacos

server:
  port: 8080