spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-route
          uri: lb://service-user
          predicates:
            - Path=/weibo/user/**
        - id: post-route
          uri: lb://service-post
          predicates:
            - Path=/weibo/post/**
        - id: friend-route
          uri: lb://service-friend
          predicates:
            - Path=/weibo/friend/**