server:
  port: 9010
spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
       server-addr: 121.199.36.161:8848
       username: nacos
       password: nacos
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
security:
  oauth2:
    client:
      client-id: client  # 客户端ID
      client-secret: secret  # 客户端密钥
      access-token-uri: = http://localhost:9010/auth/oauth/token